apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  # is ignored if KC_HOSTNAME is set
  KC_HOSTNAME_STRICT:  "{{ .Values.keycloak.hostnameStrict }}"
  # must be set if KC_HOSTNAME_STRICT is true
  KC_HOSTNAME: "https://{{ .Values.keycloak.hostname }}{{ .Values.keycloak.httpRelativePath }}"
  # if set, KC_HOSTNAME must be set to a url
  KC_HOSTNAME_ADMIN: "http://{{ .Values.keycloak.hostnameAdmin }}{{ .Values.keycloak.httpRelativePath }}"
{{- if .Values.keycloak.httpRelativePath }}
  KC_HTTP_RELATIVE_PATH: "{{ .Values.keycloak.httpRelativePath }}"
{{- end }}
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "{{ .Values.service.http.enabled }}"
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.auth.adminUsername }}"
  KC_HTTP_MANAGEMENT_PORT: "8090"
  JAVA_OPTS_APPEND: {{ printf "-Djgroups.dns.query=%s.%s.svc.cluster.local" (include "common.headlessServiceName" .) (include "common.names.namespace" .) | quote }}
  KC_HTTP_POOL_MAX_THREADS: "{{ .Values.threadPool }}"
  KC_DB: "{{ .Values.database.type }}"
