apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      serviceAccountName:  {{ include "common.serviceAccountName" . }}
      restartPolicy: {{ default "Always" .Values.restartPolicy }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: "keycloak"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- .Values.command | toYaml | nindent 16 }}
          {{- end }}
          args:
            {{ if .Values.importRealms -}}
            - "--import-realm"
            {{- end }}
            {{ range .Values.extraArgs -}}
            - {{ . }}
            {{ end }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          resources: {{- .Values.resources | toYaml | nindent 12 }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: mgmt
              containerPort: 8090
              protocol: TCP
          startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          envFrom:
            # configs
            - configMapRef:
                name: {{ template "common.names.fullname" . }}
            ## extra config
            {{- if .Values.extraConfig.create }}
            - configMapRef:
                name: "{{ .Values.extraConfig.name }}"
            {{- end }}
            ## list of external configs
            {{- range .Values.extraConfig.external }}
            - configMapRef:
                name: "{{ . }}"
            {{- end }}
            # secrets
            - secretRef:
                name: "{{ .Values.auth.secretName }}"
            {{- if .Values.extraSecret.create }}
            ## extra secret
            - secretRef:
                name: "{{ .Values.extraSecret.name }}"
            {{- end }}
            ## list of external secrets
            {{- range .Values.extraSecret.external }}
            - secretRef:
                name: "{{ . }}"
            {{- end }}
          volumeMounts:
            - mountPath: "/opt/keycloak/data/import"
              name: realm-config
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
      volumes:
        - name: realm-config
          configMap:
            name: {{ .Values.realm.name }}
        {{- with .Values.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
