{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.auth.secretName }}"
  labels:
    {{- include "common.labels" . | nindent 4 }}
  namespace: "{{ template "common.names.namespace" . }}"
type: Opaque
data:
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.auth.admin_password }}"
  KC_DB_PASSWORD: "{{ .Values.database.password }}"
  KC_RS256_PRIVATE_KEY: "{{ .Values.auth.keycloak_rs256_privateKey }}"
  KC_RS256_CERTIFICATE: "{{ .Values.auth.keycloak_rs256_certificate }}"
  KC_ADMIN_SECRET: "{{ .Values.auth.keycloak_adminSecret }}"
  KC_CLIENT_SECRET: "{{ .Values.auth.keycloak_clientSecret }}"
  KC_SERVICE_CLIENT_CERTIFICATE: "{{ .Values.auth.keycloak_serviceClientCertificate }}"
  INTERNAL_COMMUNICATION_API_KEY: "{{ .Values.auth.internal_communication_api_key }}"

{{- end }}
