annotations:
  artifacthub.io/signKey: |
    fingerprint: 9F218BE64F503809BB829626B9024AEA76E9BCB3
    url: https://burningalchemist.github.io/sql_exporter/pubkey.gpg
  git/commit-sha: 9823a55ff0621cd2ef7163271998a3e19d93e94a
apiVersion: v2
appVersion: 0.24.8
description: Database-agnostic SQL exporter for Prometheus
home: https://github.com/burningalchemist/sql_exporter
keywords:
- exporter
- servicemonitor
- sql
- metrics
maintainers:
- email: allanger@zohomail.com
  name: Nikolai Rodionov
  url: https://badhouseplants.net
name: sql-exporter
sources:
- https://github.com/burningalchemist/sql_exporter
type: application
version: 0.18.10
