apiVersion: v2
appVersion: release-1
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.3.0
description: dBildungs-IAM-server
name: dbildungs-iam-server
type: application
version: 0.0.0-release-1-20241129-1216
