replicaCount: 1

postfixImage:
  repository: my-postfix
  tag: latest
  pullPolicy: IfNotPresent
exporterImage:
  repository: my-postfix-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 587
  postfixPort: 587
  exporterPort: 9154

env:
  SMTPD_SASL_AUTH_ENABLE: "no"
  SMTPD_SASL_SECURITY_OPTIONS: "noanonymous"
  SMTPD_RECIPIENT_RESTRICTIONS: "permit_sasl_authenticated,reject"
  MECH_LIST: "plain login"
  PW_CHECK_METHOD: "saslauthd"
  RELAY_HOST: ""
  SMTP_SASL_PASSWORD_MAPS: ""

sasl_passwd_secret:
  enabled: false

postfix_exporter:
  enabled: false
