{{- if and .Values.dbpMoodle.backup.enabled (.Values.etherpadlite.enabled) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "etherpad-database"
  namespace: "{{ .Release.Namespace }}"
stringData:
  type: "{{ .Values.etherpad.externalDatabase.type }}"
  host: "{{ .Values.etherpad.externalDatabase.host }}"
  port: "{{ .Values.etherpad.externalDatabase.port }}"
  user: "{{ .Values.etherpad.externalDatabase.user }}"
  name: "{{ .Values.etherpad.externalDatabase.database }}"
{{- end }}