apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "moodle-database"
  namespace: "{{ .Release.Namespace }}"
stringData:
  type: "{{ .Values.moodle.externalDatabase.type }}"
  host: "{{ .Values.moodle.externalDatabase.host }}"
  port: "{{ .Values.moodle.externalDatabase.port }}"
  user: "{{ .Values.moodle.externalDatabase.user }}"
  name: "{{ .Values.moodle.externalDatabase.database }}"

