{{- if (.Values.dbpMoodle.secrets.useChartSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "moodle"
  namespace: "{{ .Release.Namespace }}"
stringData:
  moodle-password: {{ include "dbpMoodle.secrets.moodle_password" . }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ include "dbpMoodle.secrets.redis_password" . }}
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: {{ include "dbpMoodle.secrets.etherpad_postgresql_password" . }}
  etherpad-api-key: {{ include "dbpMoodle.secrets.etherpad_api_key" . }}
  {{- end }}
  db-password: {{ include "dbpMoodle.secrets.database_password" . }}
  db-admin-password: {{ include "dbpMoodle.secrets.database_root_password" . }}
{{- end }}
