{{- if .Values.customExtraLdifFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" $ }}-extraldif
  labels:
    app: {{ template "openldap.name" $ }}
    chart: {{ template "openldap.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- if $.Values.extraLabels }}
{{ toYaml $.Values.extraLabels | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.customExtraLdifFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}