{{ if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret.name).data.LDAP_ADMIN_USERNAME | quote }}
  LDAP_ADMIN_PASSWORD: {{ (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret.name).data.LDAP_ADMIN_PASSWORD | quote }}
  {{- if .Values.global.configUserEnabled }}
  LDAP_CONFIG_ADMIN_PASSWORD: {{ (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret.name).data.LDAP_CONFIG_ADMIN_PASSWORD | quote }}
  {{- end }}
{{- end }}
