{{- $fullName := include "openldap.fullname" . -}}

{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openldap.name" . }}
    chart: {{ include "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | nindent 4 }}
{{- end }}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ .Values.global.adminUser | b64enc | quote }}
  LDAP_ADMIN_PASSWORD: {{ .Values.global.adminPassword | b64enc | quote }}
  {{- if .Values.global.configUserEnabled }}
  LDAP_CONFIG_ADMIN_PASSWORD: {{ .Values.global.configPassword | b64enc | quote }}
  {{- end }}
{{- end }}

