{{- /* Dual Service Template: Internal (ClusterIP) + External (LoadBalancer) */ -}}
{{- $fullName := include "openldap.fullname" . -}}
{{- $lbSecretName := .Values.global.existingSecret -}}

{{- /* INTERNAL Service (ClusterIP) */ -}}
{{- if .Values.service.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.internal.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: {{ $fullName }}
    chart: {{ include "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.internal.type | default "ClusterIP" }}
  sessionAffinity: {{ .Values.service.internal.sessionAffinity | default "None" }}
  selector:
    app.kubernetes.io/component: {{ $fullName }}
    release: {{ .Release.Name }}
  ports:
    {{- if .Values.service.internal.enableLdapPort }}
    - name: ldap-port
      protocol: TCP
      port: {{ .Values.global.ldapPort }}
      targetPort: ldap-port
    {{- end }}
    {{- if .Values.service.internal.enableSslLdapPort }}
    - name: ssl-ldap-port
      protocol: TCP
      port: {{ .Values.global.sslLdapPort }}
      targetPort: ssl-ldap-port
    {{- end }}
---
{{- end }}

{{- /* EXTERNAL Service (LoadBalancer) */ -}}
{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.external.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: {{ $fullName }}
    chart: {{ include "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.external.type | default "LoadBalancer" }}
  {{- if $lbSecretName }}
  loadBalancerIP: {{ (lookup "v1" "Secret" .Release.Namespace $lbSecretName).data.LOADBALANCER_IP | b64dec | quote }}
  {{- if .Values.service.external.sourceRangesRestriction }}
  loadBalancerSourceRanges: {{ (lookup "v1" "Secret" .Release.Namespace $lbSecretName).data.LOADBALANCER_SOURCERANGES | b64dec }}
  {{- end }}
  {{- end }}
  sessionAffinity: {{ .Values.service.external.sessionAffinity | default "None" }}
  selector:
    app.kubernetes.io/component: {{ $fullName }}
    release: {{ .Release.Name }}
  ports:
    {{- if .Values.service.external.enableLdapPort }}
    - name: ldap-port
      protocol: TCP
      port: {{ .Values.global.ldapPort }}
      targetPort: ldap-port
    {{- end }}
    {{- if .Values.service.external.enableSslLdapPort }}
    - name: ssl-ldap-port
      protocol: TCP
      port: {{ .Values.global.sslLdapPort }}
      targetPort: ssl-ldap-port
    {{- end }}
{{- end }}
