{{- if .Values.clamav.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-freshclam-conf
  namespace: {{ .Release.Namespace }}
data:
  freshclam.conf: |
{{ tpl ( .Files.Get "scripts/freshclam.conf" ) | nindent 4 }}
{{- end }}