apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-plugins
  namespace: {{ .Release.Namespace }}
data:
  # contains plugin dependencies first, followed by enabled plugins
  # plugin_name:plugin_fullname:plugin_install_path:plugin_enabled
  # kaltura is installed straight into moodle install, so empty dir
  moodle-plugin-list: {{ include "dbpMoodle.pluginConfigMap.content" . | nindent 4 }}
