{{ if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailpit.fullname" . }}
  namespace: {{ include "mailpit.namespace" . }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
stringData:
  ui.htpasswd: {{ include "mailpit.generatePasswordFile" .Values.auth.ui }}
  smtp.htpasswd: {{ include "mailpit.generatePasswordFile" .Values.auth.smtp }}
  pop3.htpasswd: {{ include "mailpit.generatePasswordFile" .Values.auth.pop3 }}
  api.htpasswd: {{ include "mailpit.generatePasswordFile" .Values.auth.api }}
{{ end }}
