{{- range .Values.contact_points }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: {{ include "grafana-crs.fullname" $ }}-{{ .name }}
spec:
  name: {{ .name }}
  type: {{ .type }}
  instanceSelector:
    matchLabels:
      {{- include "grafana-crs.labels" $ | nindent 6 }}
  settings:
    {{- toYaml . | nindent 4 }}
{{- end }}
