{{- range .Values.notificationPolicies }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: {{ include "grafana-crs.fullname" $ }}-{{ .name }}
spec:
  instanceSelector:
    matchLabels:
      {{- include "grafana-crs.labels" $ | nindent 8 }}
  route:
    receiver: {{ .contact_point }}
    group_by:
      {{ .group_by }}
    routes:
    {{- range $item_inner := .routes }}
    - receiver: {{ .contact_point }}
      object_matchers:
      {{- $item_inner.matcher | nindent 8 -}}
      {{- if $item_inner.group_wait }}
      group_wait: {{ $item_inner.group_wait }}
      {{- end }}
      {{- if $item_inner.group_interval }}
      group_interval: {{ $item_inner.group_interval }}
      {{- end }}
      {{- if $item_inner.repeat_interval }}
      repeat_interval: {{ $item_inner.repeat_interval }}
      {{- end }}
    {{- end }}
{{- end }}
