{{- range .Values.datasources }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "grafana-crs.fullname" $ }}-{{ .name | lower }}
spec:
  instanceSelector:
    matchLabels:
      {{- include "grafana-crs.labels" $ | nindent 8 }}
  datasource:
    access: proxy
    name: {{ .name }}
    type: {{ .type }}
    url: {{ .url }}
    isDefault: {{ .default | default false }}
{{- end }}
