---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ include "grafana-crs.fullname" . }}
  labels: {{- include "grafana-crs.labels" . | nindent 4 }}
spec:
  version: {{ .Values.grafana.version }}
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.grafana.storage_size }}
  config:
    log:
      mode: {{ .Values.grafana.log_mode }}
    auth.generic_oauth:
      {{- if .Values.grafana.keycloak_config.enabled }}
      {{- toYaml .Values.grafana.keycloak_config | nindent 6 }}
      {{- end }}
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: sc-cert-manager-clusterissuer-letsencrypt
    spec:
      ingressClassName: {{ .Values.grafana.ingress_class_name }}
      rules:
        - host: {{ .Values.grafana.domain }}
          http:
            paths:
              - backend:
                  service:
                    name: {{ .Values.grafana.resource_name }}-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - {{ .Values.grafana.domain }}
          secretName: {{ .Values.grafana.resource_name }}-ingress-cert
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
               {{- toYaml .Values.grafana.combined_envs | nindent 16 }}
               {{- if .Values.grafana.keycloak_config.enabled }}
               {{- toYaml .Values.grafana.oauth_envs | nindent 16 }}
               {{- end }}
              # https://github.com/grafana/grafana-operator/issues/1439#issuecomment-2677822604
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
          securityContext:
            fsGroup: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: {{ .Values.grafana.resource_name }}-pvc
      strategy:
        type: Recreate
