{{- range .Values.folders }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ include "grafana-crs.fullname" $ }}-{{ .name }}
spec:
  instanceSelector:
    matchLabels:
      {{- include "grafana-crs.labels" $ | nindent 8 }}
  title: {{ .titel }}
{{- if .permissions }}
  permissions: |
    {{- .permissions | nindent 4 }}
{{ end }}
{{- end }}
