---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-kafka-envs-configmap
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
data:
 # doppelt url und broker
  KAFKA_URL: "{{ $.Values.kafka.url }}"
  KAFKA_TOPIC_PREFIX: '{{ .Release.Namespace }}-'
  KAFKA_BROKER: '{{ .Values.kafka.url }}'
  KAFKA_SSL_CA_PATH: '{{ .Values.kafka.ssl.caPath }}'
  KAFKA_SSL_CERT_PATH: '{{ .Values.kafka.ssl.certPath }}'
  KAFKA_SSL_KEY_PATH: '{{ .Values.kafka.ssl.keyPath }}'
  TLS_KEYSTORE: /jks/client.keystore.jks
  TLS_TRUSTSTORE: /jks/client.truststore.jks
  TLS_KEYSTORE_DIR: /jks
