---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-kafka-envs-configmap
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
data:
  KAFKA_URL: "{{ $.Values.kafka.url }}"
  KAFKA_TOPIC_PREFIX: '{{ .Release.Namespace }}-'
  KAFKA_TOPIC_PARTITIONS: '{{ .Values.kafka.topicPartitions }}'
  KAFKA_BROKER: '{{ .Values.kafka.url }}'
  KAFKA_SSL_ENABLED: true
  KAFKA_SSL_CA_PATH: /tls/ca.pem
  KAFKA_SSL_CERT_PATH: /tls/client-cert.pem
  KAFKA_SSL_KEY_PATH: /tls/client-key.pem
  TLS_KEYSTORE: /jks/client.keystore.jks
  TLS_TRUSTSTORE: /jks/client.truststore.jks
  TLS_KEYSTORE_DIR: /jks
