---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs:
    - get
    - list
    - create
    - watch
    - update
    - delete
    - patch
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.names.fullname" . }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}
  apiGroup: rbac.authorization.k8s.io