apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postfix
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postfix
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postfix
    spec:
      containers:
        - name: postfix
          image: "{{ .Values.postfixImage.repository }}:{{ .Values.postfixImage.tag }}"
         {{- if eq "true" (.Values.sasl_passwd_secret.enabled | toString) }}
          volumeMounts:
            - name: sasl-passwd
              mountPath: /etc/postfix/sasl_passwd
              subPath: sasl_passwd
          {{- end }}
          ports:
          - containerPort: {{ .Values.service.postfixPort }}
          env:
            - name: SMTPD_SASL_AUTH_ENABLE
              value: "{{ .Values.env.SMTPD_SASL_AUTH_ENABLE }}"
            - name: SMTPD_SASL_SECURITY_OPTIONS
              value: "{{ .Values.env.SMTPD_SASL_SECURITY_OPTIONS }}"
            - name: SMTPD_RECIPIENT_RESTRICTIONS
              value: "{{ .Values.env.SMTPD_RECIPIENT_RESTRICTIONS }}"
            - name: MECH_LIST
              value: "{{ .Values.env.MECH_LIST }}"
            - name: PW_CHECK_METHOD
              value: "{{ .Values.env.PW_CHECK_METHOD }}"
            - name: RELAY_HOST
              value: "{{ .Values.env.RELAY_HOST }}"
            {{- if ne "true" (.Values.sasl_passwd_secret.enabled | toString) }}
            - name: SMTP_SASL_PASSWORD_MAPS
              value: "{{ .Values.env.SMTP_SASL_PASSWORD_MAPS }}"
            {{- end }}
        {{- if eq "true" (.Values.postfix_exporter.enabled | toString) }}
        - name: {{ .Release.Name }}-postfix-exporter
          image: "{{ .Values.exporterImage.repository }}:{{ .Values.exporterImage.tag }}"
          ports:
          - containerPort: {{ .Values.service.exporterPort }}
        {{- end }}
      {{- if eq "true" (.Values.sasl_passwd_secret.enabled | toString) }}
      volumes:
        - name: sasl-passwd
          secret:
            secretName: postfix-sasl-secret
      {{- end }}
