apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etherpad.fullname" . }}-robots-txt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
data:
  robots.txt: |-
{{ .Values.robotsTxt | indent 4 }}
