apiVersion: v2
appVersion: DBP-0000
dependencies:
- name: moodle
  repository: https://charts.bitnami.com/bitnami
  version: 22.2.7
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.5.3
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 18.2.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.7
- alias: moodlecronjob
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: backup-cronjob
  condition: dbpMoodle.backup.enabled
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: etherpad-postgresql
  condition: etherpad-postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.7
- alias: etherpadlite
  condition: etherpadlite.enabled
  name: etherpad
  repository: file://charts/etherpad
  version: 0.1.0
- condition: sql-exporter.enabled
  name: sql-exporter
  repository: https://burningalchemist.github.io/sql_exporter/
  version: 0.6.1
description: 'This is a Helm Chart bundling some of the bitnami resources to deploy
  Moodle for DBildungsplattform. Extending them with features such as  MariaDB and
  PostgreSQL support, Horizontal Autoscaling capabilities, Redis Session Store, Etherpad-Lite.
  The Chart can be deployed without any modification but it is advised to set own
  secrets acccording to this readme. '
home: https://dbildungsplattform.github.io/dbp-moodle/
name: dbp-moodle
type: application
version: 0.0.0-dbp-0000-20241127-1255
