apiVersion: v2
appVersion: OPS-7040
dependencies:
- name: moodle
  repository: https://charts.bitnami.com/bitnami
  version: 22.2.7
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.5.3
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 18.2.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.7
- alias: moodlecronjob
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: backup-cronjob
  condition: dbpMoodle.backup.enabled
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: etherpad-postgresql
  condition: etherpadlite.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.7
- alias: etherpadlite
  condition: etherpadlite.enabled
  name: etherpad
  repository: file://charts/etherpad
  version: 0.1.0
- condition: sql-exporter.enabled
  name: sql-exporter
  repository: https://burningalchemist.github.io/sql_exporter/
  version: 0.6.1
description: A Helm chart for dBildungsplattform Moodle including customizations
name: dbp-moodle
type: application
version: 0.0.0-ops-7040-20241010-1408
