apiVersion: v2
appVersion: OPS-11339
dependencies:
- name: moodle
  repository: file://charts/moodle
  version: 27.0.5
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.5.3
- condition: valkey.enabled
  name: valkey
  repository: https://dbildungsplattform.github.io/helm-charts-registry/
  version: 3.0.1
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.38
- alias: moodlecronjob
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: backup-cronjob
  condition: dbpMoodle.backup.enabled
  name: cronjob
  repository: file://charts/cronjob
  version: 0.1.0
- alias: etherpad-postgresql
  condition: etherpad-postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.38
- alias: etherpadlite
  condition: etherpadlite.enabled
  name: etherpad
  repository: file://charts/etherpad
  version: 0.1.0
- alias: clamav
  condition: clamav.enabled
  name: clamav
  repository: https://wiremind.github.io/wiremind-helm-charts
  version: 3.5.0
- condition: sql-exporter.enabled
  name: sql-exporter
  repository: https://burningalchemist.github.io/sql_exporter/
  version: 0.6.1
description: 'This is a Helm Chart bundling some of the bitnami resources to deploy
  Moodle for DBildungsplattform. Extending them with features such as  PostgreSQL
  support, Horizontal Autoscaling capabilities, Redis Session Store, Etherpad-Lite.
  The Chart can be deployed without any modification but it is advised to set own
  secrets acccording to this readme. '
home: https://dbildungsplattform.github.io/dbp-moodle/
name: dbp-moodle
type: application
version: 0.0.0-ops-11339-20260908-1440
