apiVersion: v2
appVersion: v2.5.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.20
- condition: valkey.enabled
  name: valkey
  repository: https://dbildungsplattform.github.io/helm-charts-registry
  version: 3.0.1
description: A Helm chart for Kubernetes
name: status
type: application
version: 0.0.0-ops-11468-20260716-0948
